- name: Stop the systemd service personal portfolio frontend
  ansible.builtin.systemd:
    name: personal-portfolio-frontend
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop the systemd service api gateway
  ansible.builtin.systemd:
    name: api-gateway
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop the mongo access service
  ansible.builtin.systemd:
    name: mongo-access
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop the static media server service
  ansible.builtin.systemd:
    name: static-media-server
    state: stopped
    enabled: false
  ignore_errors: true


- name: Stop the tinyurl service
  ansible.builtin.systemd:
    name: tinyurl-server
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop the academic website service
  ansible.builtin.systemd:
    name: academic-website-server
    state: stopped
    enabled: false
  ignore_errors: true

- name: Remove the systemd service file for personal portfolio frontend
  ansible.builtin.file:
    path: /etc/systemd/system/personal-portfolio-frontend.service
    state: absent

- name: Remove the systemd service file for api gateway
  ansible.builtin.file:
    path: /etc/systemd/system/api-gateway.service
    state: absent

- name: Remove the systemd service file for mongo access service
  ansible.builtin.file:
    path: /etc/systemd/system/mongo-access.service
    state: absent

- name: Remove the systemd service file for static media server
  ansible.builtin.file:
    path: /etc/systemd/system/static-media-server.service
    state: absent

- name: Remove the systemd service file for tinyurl service
  ansible.builtin.file: 
    path: /etc/systemd/system/tinyurl-server.service
    state: absent
  ignore_errors: true

- name: Remove the systemd service file for academic website server
  ansible.builtin.file:
    path: /etc/systemd/system/academic-website-server.service
    state: absent
  ignore_errors: true

- name: Reload systemd daemon after service removal
  ansible.builtin.systemd:
    daemon_reload: true