# This is the file for repo setup to install dependicies and build the repo if need in virtual env

- name: Set up and start the personal portfolio frontend
  become: true
  become_user: ubuntu
  args:
    chdir: /home/ubuntu/personal-portfolio-frontend
  shell: |
    rm -rf .next node_modules package-lock.json
    npm install
    npm run build
    
- name : Copy the personal portfolio frontend service file
  become: true
  ansible.builtin.copy:
    src: /home/ubuntu/personal-portfolio-frontend/personal-portfolio-frontend.service
    dest: /etc/systemd/system/personal-portfolio-frontend.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable the portfolio service
  become: true
  ansible.builtin.systemd:
    name: personal-portfolio-frontend
    enabled: true

- name: Start the portfolio service
  become: true
  ansible.builtin.systemd:
    name: personal-portfolio-frontend
    state: started